### PR TITLE
Update TypeExtensions to test for an EswEventName attribute

### PR DESCRIPTION
**Pull request by spoland**
Currently the name of the type is used as the event name and it causes problems for code management. As such we need a means to override the name of this event.

This PR updates the GetEntityName method in the TypeExtensions class to include a test for a queue name passed in via an EswEventNameAttribute before returning the types full name. If it exists, it should take precedence and be used ahead of the type name.

### CODE REVIEW

**Review by dguerin — APPROVED** [review]
LGTM

**Review by VaclavK — APPROVED** [review]
lgtm

**Comment by dguerin** [comment]
@spoland we forgot the version bump

**Comment by spoland** [comment]
> 
> 
> @spoland we forgot the version bump

😑 Will sort that now in another request!

**Pull request merged**
